# Generated by Django 5.0.3 on 2024-04-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
